---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    test/class: "yes"
  labels:
    test/creation: "yes"
  name: imubit-pv
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: "false"
  type: gp2
  zones: us-east-2c
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate